### ISSUE TITLE
exposed the api token, any ideas to prevent it in frontend

### ISSUE THREAD

**Issue by jatindotdev** [Ritwikgotbugs/Quote-Fact-Generator#2]
https://github.com/Ritwikgotbugs/Quote-Fact-Generator/blob/305517cce8812ef312b9600dfac201c80ea06956/Random_quotes/await.js#L5

**Comment by Ritwikgotbugs** [comment]
> ~~Skill issue~~ 🤡

Study

**Comment by Ritwikgotbugs** [comment]
> > > ~~Skill issue~~ 🤡
> > 
> > Study
> 
> how much did you study?

Unit 2 and 4 left :)

**Comment by jatindotdev** [comment]
> > > > ~~Skill issue~~ 🤡
> > > 
> > > Study
> > 
> > how much did you study?
> 
> Unit 2 and 4 left :)

dem study study you topper

**Comment by jatindotdev** [comment]
you dumb insaan

**Comment by jatindotdev** [comment]
you are improving...

**Comment by jatindotdev** [comment]
just backwards 😂

**Comment by Ritwikgotbugs** [comment]
> just backwards 😂

stop ruining my issues

**Comment by jatindotdev** [comment]
making wrong choices abahahahahaha ded 💀

**Comment by jatindotdev** [comment]
> > just backwards 😂
> 
> 
> 
> stop ruining my issues

hehehe

**Comment by Ritwikgotbugs** [comment]
> hehehe

text karde bhai randomly idhar aakar kyu ping kar raha direct mail aati hai ahahahahaha

**Comment by Ritwikgotbugs** [comment]
> ~making wrong choices abahahahahaha ded 💀~
> 
> this is just a mazak btw
> 
> some people nowadays get offended so making sure 👍

bro wdym  💀

**Comment by jatindotdev** [comment]
> > hehehe
> 
> 
> 
> text karde bhai randomly idhar aakar kyu ping kar raha direct mail aati hai ahahahahaha
> 
> 
> 
> 
> 
> 

tabhi toh its fun was just checking my open issues and seeing yours just makes me utawala 🤡

**Comment by jatindotdev** [comment]
> > ~making wrong choices abahahahahaha ded 💀~
> 
> > 
> 
> > this is just a mazak btw
> 
> > 
> 
> > some people nowadays get offended so making sure 👍
> 
> 
> 
> bro wdym  💀

NOTHING ME BEING ME 🫶

**Comment by Ritwikgotbugs** [comment]
> > > hehehe
> > 
> > 
> > text karde bhai randomly idhar aakar kyu ping kar raha direct mail aati hai ahahahahaha
> 
> tabhi toh its fun was just checking my open issues and seeing yours just makes me utawala 🤡

close to tab bhi karunga jab keys hide ho, chahe mujhe backend mai ek naya framework kyu na bana padhe :)

**Comment by jatindotdev** [comment]
> > > > hehehe
> 
> > > 
> 
> > > 
> 
> > > text karde bhai randomly idhar aakar kyu ping kar raha direct mail aati hai ahahahahaha
> 
> > 
> 
> > tabhi toh its fun was just checking my open issues and seeing yours just makes me utawala 🤡
> 
> 
> 
> close to tab bhi karunga jab keys hide ho, chahe mujhe backend mai ek naya framework kyu na bana padhe :)

yoo i am framing it you cannot back off now

**Comment by jatindotdev** [comment]
hey skill issue what’s up

**Comment by jatindotdev** [comment]
heyy what raa

**Comment by Ritwikgotbugs** [comment]
> heyy what raa

ahahahah shut up

**Comment by jatindotdev** [comment]
> > heyy what raa
> 
> ahahahah shut up

skill issue bhai haar maan gya 😂

**Comment by Ritwikgotbugs** [comment]
> > > heyy what raa
> > 
> > 
> > ahahahah shut up
> 
> skill issue bhai haar maan gya 😂

web dev ka skill issue not mine

**Comment by jatindotdev** [comment]
> > > > heyy what raa
> > > 
> > > 
> > > ahahahah shut up
> > 
> > 
> > skill issue bhai haar maan gya 😂
> 
> web dev ka skill issue not mine

blame game nii chalega you are skill isse

**Comment by Ritwikgotbugs** [comment]
> > > > > heyy what raa
> > > > 
> > > > 
> > > > ahahahah shut up
> > > 
> > > 
> > > skill issue bhai haar maan gya 😂
> > 
> > 
> > web dev ka skill issue not mine
> 
> blame game nii chalega you are skill isse

i am the skill, web dev is the issue

**Comment by Ritwikgotbugs** [comment]
mera koi employer mere ye issue kholega to reject kardega bhai tu skill issue bolna band kar bhai ill kill you

**Comment by jatindotdev** [comment]
> > > > > > heyy what raa
> > > > > 
> > > > > 
> > > > > ahahahah shut up
> > > > 
> > > > 
> > > > skill issue bhai haar maan gya 😂
> > > 
> > > 
> > > web dev ka skill issue not mine
> > 
> > 
> > blame game nii chalega you are skill isse
> 
> i am the skill, web dev is the issue

skill huh? where is the skill, i can onli see issue in you

**Comment by jatindotdev** [comment]
> mera koi employer mera ye issue kholega to reject kardega bhai tu skill issue bolna band kar bhai ill kill you

ahahahah krne de

**Comment by jatindotdev** [comment]
wait employer, kaun dera job tereko lmao 😂

**Comment by Ritwikgotbugs** [comment]
> > > > > > > heyy what raa
> > > > > > 
> > > > > > 
> > > > > > ahahahah shut up
> > > > > 
> > > > > 
> > > > > skill issue bhai haar maan gya 😂
> > > > 
> > > > 
> > > > web dev ka skill issue not mine
> > > 
> > > 
> > > blame game nii chalega you are skill isse
> > 
> > 
> > i am the skill, web dev is the issue
> 
> skill huh? where is the skill, i can onli see issue in you

zaroor zaroor

**Comment by Ritwikgotbugs** [comment]
> wait employer?, kaun dera job tereko lmao 😂😂😂

okay :(
