### ISSUE TITLE
How can we stop this from happening?

### ISSUE THREAD

**Issue by jatindotdev** [Ritwikgotbugs/Quote-Fact-Generator#4]
this shouldn't happen once one request is sent

https://github.com/Ritwikgotbugs/Quote-Fact-Generator/assets/59236972/be6de43d-cccf-434d-8096-5de365ee1dd3

**Comment by Ritwikgotbugs** [comment]
I don't quiet understand what exactly is happening, can you elaborate on it a little bit more?

**Comment by jatindotdev** [comment]
what i meant to show is when bombarding the button with clicks it generates a lot of requests, and oncee each function completes it changes the text even if you leave the page still

**Comment by jatindotdev** [comment]
> I don't quiet understand what exactly is happening, can you elaborate on it a little bit more?

try clicking the button multiple times in a sec, then wait for some time

**Comment by Ritwikgotbugs** [comment]
> what i meant to show is when bombarding the button with clicks it generates a lot of requests, and oncee each function completes it changes the text even if you leave the page still

So to prevent this I just need to have a time out on the button as to whenever it is clicked, the button is disabled and the response is fetched, it is enabled again. Am it right?

**Comment by jatindotdev** [comment]
> > what i meant to show is when bombarding the button with clicks it generates a lot of requests, and oncee each function completes it changes the text even if you leave the page still
> 
> So to prevent this I just need to have a time out on the button as to whenever it is clicked, the button is disabled and the response is fetched, it is enabled again. Am it right?

yes. there could be other possible solutions want you to look around them
